version: '3.9'

volumes:
  minio_storage:

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-22T00-33-43Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
